name: Fill cache

on: push

jobs:
    fill-cache:
        runs-on: ubuntu-latest
        container: 
              image: rocker/r-ver:4.4.0

        strategy:
            matrix:
                id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Display session info
              run: |
                Rscript -e 'sessionInfo()'

            - name: Cache data
              uses: actions/cache@v4
              id: cache-data
              with:
                key: data-${{ matrix.id }}
                path: ./data.rds

            - name: Generate data
              if: steps.cache-data.outputs.cache-hit != 'true'
              shell: Rscript {0}
              run: |
                # Matrix of size ~1 GB
                id <- ${{ matrix.id }}
                data <- floor(rep(id, 1.5e8) + runif(1.5e8)*.1)
                saveRDS(data, "data.rds", compress = FALSE)

            - name: Load the data
              run: Rscript --vanilla -e 'readRDS("data.rds") |> head()'
                

